### ISSUE TITLE
突然のissue失礼します。

### ISSUE THREAD

**Issue by niidahikaru** [noplan1989/all-you-need-is-tuna#1]
突然のissue失礼します。
趣味で個人開発をしている新田と申します。SNSなどもやられていなかったのでこちらからご連絡させて頂きました。
laravelでwebsocket実装をするにあたりこの記事を拝見させて頂きました。
https://qiita.com/nishinoshake/items/1be777f1d5f4f36ebe09#laravel-echo-server%E3%81%AE%E3%82%A4%E3%83%B3%E3%82%B9%E3%83%88%E3%83%BC%E3%83%AB

本番環境構築にあたりwebsocket通信が上手くいかず、もしお時間許すようでしたらいくつかご質問させていただきたいのでご返信いただければ幸いです。

**Comment by nishinoshake** [comment]
@niidahikaru  WebSocketまわりに詳しいわけではありませんが、わかる範囲でお答えしますよ！

**Comment by nishinoshake** [comment]
@niidahikaru その後どうでしょうか...？上手くいったようでしたら、一旦クローズさせてもらいます！
